Make timer clock soure configurable
robert-burger/libosal pull request #5
Opened 2024-09-18 12:58 UTC by marcfir

Hi Robert,
here is a suggestion for configuring the clock source.

2024-09-18 13:28 UTC, robert-burger requested changes
1. this is meant to use CLOCK_MONOTIC, CLOCK_REALTIME, ... directly from system headers. should we add some defines to that os-specific values like e.g.  LIBOSAL_CLOCK_MONOTONIC?
2. can you please fix indenting back to 4 spaces? changes are also a little hard to read now...

2024-09-18 13:28 UTC, robert-burger commented on src/posix/timer.c
> +    int ret = clock_nanosleep(LIBOSAL_CLOCK, 0, &ts, &rest);
should also be global_clock_id instead of LIBOSAL_CLOCK

2024-09-20 09:58 UTC, marcfir commented
1. I thought about this. Linux has more clock types than the POSIX standard, so how would you expose the clock ID's? Just the ones from POSIX and if you want to use an OS specific one you can include the time.h header? 

2. Oh yeah, I will fix that.

3. I added a little test locally that configures different times. The test is not really deterministic because getting two times and comparing the difference to an upper bound could be interrupted by the scheduler. But I had no idea how to make the test more deterministic. I can add the test if you like.

2024-09-20 12:54 UTC, marcfir commented
What to do with the `pthread_condattr_setclock()` calls?

2024-09-25 11:55 UTC, robert-burger commented
> What to do with the `pthread_condattr_setclock()` calls?

couldn't we do e.g. osal_timer_get_clock_source ? and return the internal clock id integer number?

2024-09-26 12:27 UTC, marcfir commented
> > What to do with the `pthread_condattr_setclock()` calls?
> 
> couldn't we do e.g. osal_timer_get_clock_source ? and return the internal clock id integer number?

Good point. I added the call. It should work.

2024-09-27 05:58 UTC, robert-burger approved these changes
lgtm

2024-09-27 05:58 UTC, merged

2024-09-27 05:59 UTC, robert-burger commented
thanks